-- 코드를 입력하세요
SELECT C.AUTHOR_ID, C.AUTHOR_NAME, A.CATEGORY, SUM(B.SALES * A.PRICE) AS TOTAL_SALES FROM BOOK A JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID JOIN AUTHOR C ON A.AUTHOR_ID = C.AUTHOR_ID
WHERE MONTH(B.SALES_DATE) = 1
GROUP BY C.AUTHOR_NAME, A.CATEGORY
ORDER BY C.AUTHOR_ID, A.CATEGORY DESC